# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 15:15
from __future__ import unicode_literals

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Home.models.to_),
        ),
    ]
